# Generated by Django 3.0.3 on 2020-04-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_auto_20200406_1527'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
