# Generated by Django 3.0.3 on 2020-04-08 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0009_userimage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userimage',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userimage',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
