# Generated by Django 3.0.3 on 2020-04-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0011_auto_20200408_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users'),
        ),
    ]
